groups:
  - name: DemoAlerts
    rules:
      - alert: InstanceDown
        expr: up{job="nginx"} == 0
        for: 1m
        labels:
          severity: low
        annotations:
          summary: 'Alert with low severity.'

      - alert: InstanceDownCritical
        expr: up{job="nginx"} == 0
        for: 5m
        labels:
          severity: high
        annotations:
          summary: 'Alert with high severity.'
