global:
  scrape_interval: 5s
  scrape_timeout: 5s

rule_files:
  - alert.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /nginx_status
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: '${com.docker.compose.service}'
      - source_labels: [__address__]
        target_label: __address__
        replacement: 'nginx:80'
