groups:
  - name: DemoAlerts
    rules:
      - alert: InstanceDown
        expr: nginx_up{job="services"} < 1
        for: 1m
        labels:
          severity: low
        annotations:
          summary: 'Alert with low severity.'

      - alert: InstanceDownCritical
        expr: nginx_up{job="services"} < 1
        for: 5m
        labels:
          severity: high
        annotations:
          summary: 'Alert with high severity.'