global:
  scrape_interval: 5s
  scrape_timeout: 5s

rule_files:
  - alert.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'nginx:80'
          - 'nginx-prometheus-exporter:9113'

  - job_name: webserver
    metrics_path: /
    static_configs:
      - targets:
          - 'nginx:80'